### ISSUE TITLE
Test run of tool_vforwater_loader locally

### ISSUE THREAD

**Issue by elnazazmi** [VForWaTer/tool_vforwater_loader#2]
I ran the tool locally and beforehand used an ssh tunnel to connect to the server database. I checked already the database connection with this command: "psql -h localhost -p 5432 -U postgres" and it works.
Here I upload the logs to solve this issue. 
[logs.log](https://github.com/VForWaTer/tool_vforwater_loader/files/14346880/logs.log)

**Comment by elnazazmi** [comment]
When I add "--network host" to my docker run command, I could connect to the database but the error is that the "database "metacatalog" does not exist".
Here I upload the trace back.
[net_host.log](https://github.com/VForWaTer/tool_vforwater_loader/files/14356760/net_host.log)

**Comment by elnazazmi** [comment]
Ah Ok, I tried to pass the URI to connect with "metacatalog-dev", and this time the error is about "column datasources.variable_names does not exist".
Here is the Traceback.
[metacat.log](https://github.com/VForWaTer/tool_vforwater_loader/files/14357221/metacat.log)

**Comment by mmaelicke** [comment]
OK, that's actually good, because this is on us. We did not update the productive database to the latest changes. @AlexDo1, we should take care of that soon.

We basically had to add a few columns, to handle the different naming conventions in hyras, radolan and era5-land data.
We will come back to you as soon as this is done.

**Comment by AlexDo1** [comment]
I also added the database migration for the new columns in datasource here: https://github.com/VForWaTer/metacatalog/pull/307

We would just need to execute the migration on the server. I just tried to do that, but somehow I cannot login to the jupyterhub.  
I still can login on the server via SSH but there I cannot activate my metacatalog environment, I think this is because Python is broken on the server, `python --version` gives `Python 2.7.5`.  
And `metacatalog --version` gives `/home/qt7760/env/mc-env/bin/metacatalog: /home/qt7760/env/mc-env/bin/python3.10: Defekter Interpreter: Datei oder Verzeichnis nicht gefunden`  

So I think we need the help of @joergmeyer-kit here, or I am doing something wrong.  

I will be on vacation from now until Sunday, so I cannot take care of that until Monday.

**Comment by elnazazmi** [comment]
I could just login to jupyterhub and use my python 3.10 virtual environment, but the direct call of "python" in terminal gives the "command not found" output.

**Comment by joergmeyer-kit** [comment]
> I could just login to jupyterhub and use my python 3.10 virtual environment, but the direct call of "python" in terminal gives the "command not found" output.

works for me:
![jupyter_Screenshot_20240223_101519](https://github.com/VForWaTer/tool_vforwater_loader/assets/23399029/cb6b4ac7-ca57-4567-b990-cacc359154c7)

**Comment by elnazazmi** [comment]
Now, it works for me also without activating the virtual env:
![image](https://github.com/VForWaTer/tool_vforwater_loader/assets/20579300/022b48f5-9bdc-4e95-bf2f-b5edd088008e)

**Comment by mmaelicke** [comment]
Yeah, Thanks!

The column has to be filled manually, as the existing data sources did Not have the column, at the time they were created. We Need to do that First

**Comment by AlexDo1** [comment]
Okay, I just added `variable_names` and `dimension_names` manually to the HYRAS datasources.  
For other datasets we need to come up with a strategy on what to put into the datasource fields.  
For HYRAS data, these problems should be fixed for now.

**Comment by MarcusStrobl** [comment]
Might the new `variable_names` be relevant for the filter or the preview?

**Comment by elnazazmi** [comment]
I ran the docker after these updates and report here the logs:
[errors.log](https://github.com/VForWaTer/tool_vforwater_loader/files/14405612/errors.log)
[metacat_260224.log](https://github.com/VForWaTer/tool_vforwater_loader/files/14405614/metacat_260224.log)
[processing.log](https://github.com/VForWaTer/tool_vforwater_loader/files/14405615/processing.log)

**Comment by mmaelicke** [comment]
> Might the new `variable_names` be relevant for the filter or the preview?

Actually not. These *names* are used to reference the columns, dimensions or layers of the respective data source, in case the actual data is not stored in the database itself. This is information, that is neither useful for the user, nor do I think that there is a use case, where the frontend has to be aware of these informations.

**Comment by mmaelicke** [comment]
> I ran the docker after these updates and report here the logs: [errors.log](https://github.com/VForWaTer/tool_vforwater_loader/files/14405612/errors.log) [metacat_260224.log](https://github.com/VForWaTer/tool_vforwater_loader/files/14405614/metacat_260224.log) [processing.log](https://github.com/VForWaTer/tool_vforwater_loader/files/14405615/processing.log)

The error looks to me like there is something off with the harmonization of the data. 
Using the time series data is completely untested, as we focused on the hyras netCDF so far. Following the logs I would have expected that a `datasets/sap_flow_1.parquet`, `datasets/sap_flow_2.parquet` and `datasets/air_temperature_19.parquet` have been loaded, which is already 'result'. @elnazazmi  can you confirm that these files are missing, after the tool finished?

It might be an easy fix, as the file extension got missing during loading, no idea why, but also not too bad, given that it is not tested so far. I will let you know, when ingesting and processing time series data is stable from my side.

**Comment by elnazazmi** [comment]
The mentioned files are created as .json and .parquet types in the datasets folder.
Also, dataset.db, reference_area.ascii and reference_area.geojson are created.

**Comment by mmaelicke** [comment]
Perfect! Then, stuff works now and you basically only need to wait until we release new tool versions
